// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmuSuTCLZX6K2Sq57WQkWH1PIJ_f-JxLY',
    appId: '1:372122830173:web:f7e8860dd67573c688d4b4',
    messagingSenderId: '372122830173',
    projectId: 'fair-games-47cad',
    authDomain: 'fair-games-47cad.firebaseapp.com',
    storageBucket: 'fair-games-47cad.appspot.com',
    measurementId: 'G-DMY8DHLYE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LgUg5mqPda1TmQdcyOzK7RnR5YiWQy4',
    appId: '1:372122830173:android:ee4749762345495a88d4b4',
    messagingSenderId: '372122830173',
    projectId: 'fair-games-47cad',
    storageBucket: 'fair-games-47cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3dhitQleiOHcGQLTuPZ30qIREFd_uW-0',
    appId: '1:372122830173:ios:0c52f2c492f5a8f988d4b4',
    messagingSenderId: '372122830173',
    projectId: 'fair-games-47cad',
    storageBucket: 'fair-games-47cad.appspot.com',
    iosBundleId: 'com.originswift.fairgames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3dhitQleiOHcGQLTuPZ30qIREFd_uW-0',
    appId: '1:372122830173:ios:9d977aef2d86fdf588d4b4',
    messagingSenderId: '372122830173',
    projectId: 'fair-games-47cad',
    storageBucket: 'fair-games-47cad.appspot.com',
    iosBundleId: 'com.example.fairgames',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmuSuTCLZX6K2Sq57WQkWH1PIJ_f-JxLY',
    appId: '1:372122830173:web:2731725c43a8621888d4b4',
    messagingSenderId: '372122830173',
    projectId: 'fair-games-47cad',
    authDomain: 'fair-games-47cad.firebaseapp.com',
    storageBucket: 'fair-games-47cad.appspot.com',
    measurementId: 'G-1NT7V238MV',
  );

}